name: device_screenshot
description: "A Flutter plugin that can helps you to take screenshot your overall device."
version: 0.0.9
homepage: https://github.com/P-B1101/device_screenshot.git

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.flutter.device_screenshot
        pluginClass: DeviceScreenshotPlugin
